---
- name: Apply first configuration to centos5 nodes
  become: yes
  hosts: all
  gather_facts: False
  vars:
    proxy: http://proxy:3128
    yum_cfg: /etc/yum.conf
  tasks:
    - name: add proxy
      raw:  if [ ! $(egrep "^proxy=" /etc/yum.conf) ]; then echo "proxy={{ proxy }}" >> {{ yum_cfg }}; fi
      when: proxy is defined

- name: raw install
      raw: yum install -y python-simplejson
