---
- name: Apply initial conditions to connect ansible on centos 5 nodes
  become: yes
  hosts: all
  gather_facts: False
  vars:
    proxy: http://proxy:3128/
    yum_cfg: /etc/yum.conf
    EOL: "{{ lookup('pipe', 'date +%Y') }}"
  tasks:
    - name: add proxy
      raw:  grep -E "^proxy={{ proxy }}" /etc/yum.conf -q
      register: proxy_result
      ignore_errors: True

    - name: set proxy on {{ yum_cfg }}
      raw: sed -i "s|proxy=.*|proxy={{ proxy }}|g" {{ yum_cfg }}
      when: proxy_result|failed and proxy is defined

    - name: ensure that simplejson is installed.
      raw: rpm -qa | grep python-simplejson -q
      register: proxy_python
      ignore_errors: True

    - name: raw install simplejson
      raw: yum install -y python-simplejson
      when: python_result|failed and EOL|int < 2020
