---
- name: Apply initial conditions to connect ansible on centos 5 nodes
  become: yes
  hosts: all
  gather_facts: False
  vars:
    proxy: http://proxy:3128/
    yum_cfg: /etc/yum.conf
  tasks:
    - name: add proxy
      raw:  grep -E "^proxy={{ proxy }}" /etc/yum.conf -q
      register: result
      ignore_errors: True

    - name: set proxy on {{ yum_cfg }}
      raw: sed -i "s|proxy=.*|proxy={{ proxy }}|g" {{ yum_cfg }}
      when: result|failed and proxy is defined

    - name: raw install simplejson
      raw: yum install -y python-simplejson
      when: result|failed
