---
- name: Apply initial conditions to connect ansible on ubuntu xenial nodes
  become: yes
  hosts: all
  gather_facts: False

  vars:
    proxy: http://proxy:3128
    apt_cfg: /etc/apt/apt.conf.d/30proxy

  tasks:
    - name: ensure that proxy is written on apt.conf.d/*
      raw: grep -E "Acquire::http[s]::Proxy\s+\"{{ proxy }}\";" /etc/apt/* -RIq
      register: result
      ignore_errors: True

    - name: set Acquire Proxy on apt.conf.d/30proxy
      raw: >
        echo -e "Acquire::https::Proxy \"{{ proxy }}\";\nAcquire::http::Proxy \"{{ proxy }}\";" > {{ apt_cfg }}
      args:
        executable: /bin/bash
      when: result|failed and proxy is defined

    - name: raw install python
      raw: apt-get -y install python
      when: result|failed
