---
- name: Apply initial conditions to connect ansible on ubuntu xenial nodes
  become: yes
  hosts: all
  gather_facts: False

  vars:
    proxy: http://proxy:3128
    apt_cfg: /etc/apt/apt.conf.d/30proxy
    EOL: "{{ lookup('pipe', 'date +%Y') }}"

  tasks:
    - name: ensure that proxy is written on apt.conf.d/*
      raw: grep -E "Acquire::http[s]::Proxy\s+\"{{ proxy }}\";" /etc/apt/* -RIq
      register: proxy_result
      ignore_errors: True

    - name: set Acquire Proxy on apt.conf.d/30proxy
      raw: >
        echo -e "Acquire::https::Proxy \"{{ proxy }}\";\nAcquire::http::Proxy \"{{ proxy }}\";" > {{ apt_cfg }}
      args:
        executable: /bin/bash
      when: proxy_result|failed and proxy is defined

    - name: ensure that python is installed
      raw: which python
      register: python_result
      ignore_error: True
      
    - name: raw install python
      raw: apt-get -y install python
      when: python_result|failed and EOL|int < 2020

    - name: Check your python's End of Life
      debug:
        msg: huh, your server has python2, go over to python3 ...
      when: EOL|int >= 2020
