---
# how to install python
- name: how to install python2 on ubuntu 16 to use ansible.
  become: yes
  hosts: all
  gather_facts: False

  vars:
    proxy: http://proxy:3128
    apt_cfg: /etc/apt/apt.conf.d/02proxy

  tasks:
    - name: add proxy
      raw: "{{ item }}"
      with_items:
        - echo "Acquire::http::proxy \"{{ proxy }}\";" > {{ apt_cfg }}
        - echo "Acquire::https::proxy \"{{ proxy }}\";" >> {{ apt_cfg }}
      when: proxy is defined
      
    - name: raw install python
      raw: apt-get -y install python
