---
# how to install python
- name: how to install python2 on ubuntu 16 to use ansible.
  become: yes
  hosts: all
  gather_facts: False

  vars:
    proxy: http://proxy:3128
    apt_cfg: /etc/apt/apt.conf.d/02proxy

  tasks:
    - name: add proxy
      raw: >
        echo -e "" > {{ apt_cfg }}
        if ! grep "Proxy" /etc/apt/* -RIq; then
          echo "Acquire::{{ item }}::Proxy \"{{ proxy }}\";" >> {{ apt_cfg }}
        fi
      with_items:
        - http
        - https
      args:
        executable: /bin/bash
      when: proxy is defined
      
    - name: raw install python
      raw: apt-get -y install python
