---
- name: Ensure that Python2 packages are present
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - {{ vim_packages }}
    - {{ git_packages }}
    - {{ python_packages }}
