---
- name: Ensure that Python2 packages are present
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python-dev
    - python-pip
    - docker-py
    - git
    - tig
    - vim
    - vim-syntax-docker
    - vim-python-jedi
    - vim-editorconfig
