---
- name: Ensure that Python2 packages are present
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - {{ system_packages }}
    - {{ vim_packages }}
    - {{ git_packages }}
    - {{ python_packages }}
    - {{ haskell_pakeges }}
    - {{ ocaml_packges }}
    - {{ shellscript_packages }}
