---
- name: Set my profile
  file:
    path: /etc/profile.d/{{ my_profile }}
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Set env variables in profile.d/*
  lineinfile:
    dest: /etc/profile.d/{{ my_profile }}
    create: yes
    line: "{{ item }}"
    state: present
  with_items:
    - {{ alias_profile }}
    - {{ export_lists }}
