---
- block:
  # !-certify swapfile size
  - name: Write swapfile
    command: fallocate -l {{ swapfile_size }} {{ swapfile_path }}
    args:
      creates: "{{ swapfile_path }}"
    register: write_swapfile

  - name: Set swapfile permission 600
    file:
      path: "{{ swapfile_path }}"
      mode: 0600

  - name: Create swapfile
    command: mkswap {{ swapfile_path }}
    when: write_swapfile.changed

  - name: Enable swapfile
    command: swapon {{ swapfile_path }}
    when: ansible_swaptotal_mb < 1

  - name: Write swap entry in /etc/fstab
    mount:
      name: none
      src: "{{ swapfile_path }}"
      fstype: swap
      opts: sw
      passno: 0
      dump: 0
      state: present

  # !-certify swapfile size
  when: swapfile_size != false
